Fix server error when querying for a non-active discount code
all-dressed/laravel-sdk pull request #1
Opened 2023-06-19 17:54 UTC by ccharette

<img width="1704" alt="Screenshot 2023-06-19 at 1 51 42 PM" src="https://github.com/all-dressed/laravel-sdk/assets/58125917/1aa35ef2-f0ae-400f-b8a3-e7bea7b27b1f">

2023-06-19 19:39 UTC, chinleung commented on src/Builders/DiscountBuilder.php
> +    protected function throw(Throwable $exception): void
Pourquoi tu moves la fonction en haut du `delete` ? 🧐

2023-06-19 19:39 UTC, chinleung commented on src/Builders/DiscountBuilder.php
> +            abort_unless($exception->getCode() != 404, 404);
En fait je veux que le SDK throw une exception. Il faudrait plutôt que l'app du client catch l'exception et fait une 404 au lieu d'une 500.

2023-06-21 20:44 UTC, ccharette commented on src/Builders/DiscountBuilder.php
> +    protected function throw(Throwable $exception): void
Ah.. mon phpstorm move les fonctions on save ..

2023-06-28 18:38 UTC, chinleung requested changes

2023-06-28 18:38 UTC, chinleung commented on src/Builders/DiscountBuilder.php
> +     * @param  \Throwable  $exception
C'est reversed compared au actual order dans la fonction. 🤔

2023-07-05 17:13 UTC, chinleung requested changes

2023-07-05 17:13 UTC, chinleung commented on src/Builders/DiscountBuilder.php
> +     * @param  string|null $code
C'est ton PHPStorm qui enlève le space avant la variable ? 🧐

2023-07-12 14:42 UTC, chinleung requested changes

2023-07-24 16:41 UTC, chinleung approved these changes

2023-07-24 16:41 UTC, merged