Support for transactional orders
all-dressed/laravel-sdk pull request #14
Opened 2024-11-04 20:41 UTC by Shokushu

2024-11-11 17:01 UTC, chinleung requested changes

2024-11-11 18:22 UTC, Shokushu commented on src/Menu.php
> +    }
Hm, ça semble unused anyways 🤔

2024-11-11 18:28 UTC, Shokushu commented on src/Builders/MenuBuilder.php
> +        return $this->withOption('date', $date);
On a pas de méthode `forMenu()` dans le `MenuBuilder`, mais j'assume que tu voulais juste dire la méthode `for()` qui accepte un `Menu` 😄

2024-11-13 17:03 UTC, chinleung requested changes

2024-11-13 17:03 UTC, chinleung commented on src/Builders/OrderBuilder.php
> +                'packages' => [$packages],
Si on n'a pas de `$packages` dans la transaction, on passe `[null]`, qui va throw une erreur 422.

On doit aussi make sure de ne pas wrap une autre fois si on reçoit déjà le `$packages` en array via les paramètres de la fonction.

```php
OrderBuilder::make()->create(
    // ...
    packages: [
        [
            'id' => '...',
            'quantity' => 1,
        ]
    ]
);
```

Ce code va envoyer le payload:

```
[
    [
        [
            'id' => '...',
            'quantity' => 1,
        ]
    ]
]
```

On peut utiliser [Arr::wrap](https://laravel.com/docs/master/helpers#method-array-wrap)` au lieu de `[$packages]`. 😄

2024-11-14 18:56 UTC, merged